/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global virtual class ADV_Adapter {
    global ADV_Adapter() {

    }
    global void configAccountForContact(Account a) {

    }
    global void configAccountTDTM(List<SObject> listNew, List<SObject> listOld, String action) {

    }
    global virtual List<npsp__Trigger_Handler__c> getDefaultTdtmConfigNpspRecords(List<npsp__Trigger_Handler__c> listTH) {
        return null;
    }
    global void moveOppsToContactAccount(Map<Id,Id> mapContactIdAccountIdNew, Map<Id,Id> mapContactIdAccountIdOld) {

    }
    global void rollupAccounts(List<Id> listAccountId) {

    }
}
