/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global interface BDI_IMatchDonations {
    void match(npsp.BDI_DataImportService param0, List<npsp__DataImport__c> param1, Map<Id,Opportunity> param2, Map<Id,npe01__OppPayment__c> param3);
}
