/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class ERR_Handler_API {
    global ERR_Handler_API() {

    }
    global static void processError(Exception e, String context) {

    }
global enum Context {ADDR, AFFL, ALLO, BDE, BDI, CON, CONV, CRLP, HH, LD, LVL, OPP, PMT, RD, REL, RLLP, SCH, STTG, TDTM, USER}
}
