/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global interface HH_INaming {
    String getExampleName(npsp__Household_Naming_Settings__c param0, String param1, List<Contact> param2);
    String getHouseholdFormalGreeting(List<Contact> param0);
    String getHouseholdInformalGreeting(List<Contact> param0);
    String getHouseholdName(List<Contact> param0);
    Set<String> setHouseholdNameFieldsOnContact();
}
