/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class HH_ManageHousehold_EXT {
    global HH_ManageHousehold_EXT() {

    }
    @RemoteAction
    global static List<Contact> findContacts(String subString, String state) {
        return null;
    }
    @RemoteAction
    global static String remoteAddMember(Id cid, Boolean includeHH, String state) {
        return null;
    }
    @RemoteAction
    global static String remoteRemoveMember(Id cid, String state) {
        return null;
    }
    @RemoteAction
    global static String remoteSave(String state) {
        return null;
    }
    @RemoteAction
    global static String remoteSetNaming(Boolean aN, String nN, Boolean aFG, String nFG, Boolean aIG, String nIG, String state) {
        return null;
    }
}
