/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class REL_RelationshipsViewer_CTRL {
    @RemoteAction
    global static npsp.REL_RelationshipsViewer_CTRL.RelationshipInfo getRelationshipInfo() {
        return null;
    }
    @RemoteAction
    global static List<npsp.REL_RelationshipsViewer_CTRL.Node> getRelationships(Id cid, Boolean isInitialLoad, List<String> relIds) {
        return null;
    }
global class Node {
    global Node() {

    }
}
global class RelationshipInfo {
}
}
