/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class TDTM_Config_API {
    global TDTM_Config_API() {

    }
    @InvocableMethod(label='Disable NPSP Rollup Triggers')
    global static void disableAllRollupTriggers() {

    }
    global static List<npsp__Trigger_Handler__c> getCachedRecords() {
        return null;
    }
    global static List<npsp__Trigger_Handler__c> getDefaultRecords() {
        return null;
    }
}
