/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class UTIL_RecordTypes_API {
    global UTIL_RecordTypes_API() {

    }
    global static Id GetRecordTypeId(String objectName, String recordTypeName) {
        return null;
    }
    global static Set<Id> GetRecordTypeIdSet(String objectName, Set<String> recordTypeNameSet) {
        return null;
    }
    global static String GetRecordTypeName(String objectName, String recordTypeId) {
        return null;
    }
}
