/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global virtual class UTIL_RecordTypeSettingsUpdate {
    global static npsp.UTIL_RecordTypeSettingsUpdate getInstance() {
        return null;
    }
    global virtual void updateSettings() {

    }
}
