/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class UTIL_CustomSettings_API {
    global UTIL_CustomSettings_API() {

    }
    global static npe5__Affiliations_Settings__c getAffiliationsSettings() {
        return null;
    }
    global static npsp__Allocations_Settings__c getAllocationsSettings() {
        return null;
    }
    global static npsp__Batch_Data_Entry_Settings__c getBDESettings() {
        return null;
    }
    global static npe01__Contacts_And_Orgs_Settings__c getContactsSettings() {
        return null;
    }
    global static npsp__Data_Import_Settings__c getDataImportSettings() {
        return null;
    }
    global static npsp__Error_Settings__c getErrorSettings() {
        return null;
    }
    global static npsp__Household_Naming_Settings__c getHouseholdNamingSettings() {
        return null;
    }
    global static npo02__Households_Settings__c getHouseholdsSettings() {
        return null;
    }
    global static npe03__Recurring_Donations_Settings__c getRecurringDonationsSettings() {
        return null;
    }
    global static npe4__Relationship_Settings__c getRelationshipSettings() {
        return null;
    }
}
