/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global virtual class VOL_CTRL_VolunteersSignup {
    global Contact contact {
        get;
        set;
    }
    global String StrSaveResult {
        get;
        set;
    }
    global String strURLtoCSSFile {
        get;
        set;
    }
    global VOL_CTRL_VolunteersSignup() {

    }
    global static void CodeCoverageTests() {

    }
    global virtual System.PageReference Save() {
        return null;
    }
}
