/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class Relationships_INST implements System.InstallHandler {
    global static String RECIPROCAL_DEFAULT_RESOURCE_NAME;
    global Relationships_INST() {

    }
    global void onInstall(System.InstallContext context) {

    }
}
