/*
Esse campo é gerado e não é o código fonte real para essa
classe global gerenciada.
Esse arquivo somente leitura mostra os construtores globais de classe,
métodos, variáveis e propriedades.
Para permitir a compilação do código, todos os métodos retornam nulo.
*/
global class Households {
    global Households() {

    }
    webService static String getHouseholdLastTransaction(Id householdId) {
        return null;
    }
    webService static String getHouseholdTransactionTotal(Id householdId) {
        return null;
    }
}
